// Extracts DATA.rice / DATA.breakfast (id, name, base64 img) out of the
// prototype HTML's giant inline <script> block and writes:
//   - supabase/seed_foods.sql   (INSERT statements, image_url = base64 data URI)
//   - public/foods.json         (same data, used only for local sanity checks)
//
// Usage: node scripts/extract-foods.mjs <path-to-prototype.html>
import { readFileSync, writeFileSync } from 'node:fs';
import { createContext, runInContext } from 'node:vm';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const srcPath = process.argv[2];
if (!srcPath) {
  console.error('Usage: node scripts/extract-foods.mjs <path-to-vuiapp-yokowo-*.html>');
  process.exit(1);
}

const html = readFileSync(srcPath, 'utf8');

const startMarker = 'const DATA = {';
const start = html.indexOf(startMarker);
if (start === -1) throw new Error('Could not find "const DATA = {" in the HTML file.');

const endMarker = 'CONFIG — Admin';
const endCommentStart = html.indexOf(endMarker, start);
if (endCommentStart === -1) throw new Error('Could not find the CONFIG section after DATA.');

// Walk back from the CONFIG comment to the closing "};" of the DATA object.
const closeIdx = html.lastIndexOf('};', endCommentStart);
if (closeIdx === -1) throw new Error('Could not find closing "};" of DATA object.');

const dataSrc = html.slice(start, closeIdx + 1); // "const DATA = { ... };"

const sandbox = {};
createContext(sandbox);
runInContext(dataSrc + '\nthis.__DATA__ = DATA;', sandbox);
const DATA = sandbox.__DATA__;

if (!DATA || !Array.isArray(DATA.rice) || !Array.isArray(DATA.breakfast)) {
  throw new Error('Parsed DATA object does not look right (missing rice/breakfast arrays).');
}

function esc(s) {
  return String(s).replace(/'/g, "''");
}

function buildRows(list, category) {
  return list.map((m, i) => ({
    id: m.id,
    name: m.name,
    category,
    image_url: m.img || null,
    display_order: i + 1
  }));
}

const rows = [...buildRows(DATA.rice, 'rice'), ...buildRows(DATA.breakfast, 'breakfast')];

const sql = [
  '-- Auto-generated by scripts/extract-foods.mjs — do not hand-edit.',
  '-- Re-run the script instead if the prototype\'s food list changes.',
  '-- NOTE: image_url below is a temporary base64 data URI copied straight from',
  '-- the prototype. Swap these for real CDN/Supabase Storage URLs before launch',
  '-- (see handoff doc: "Đổi từ base64 nhúng sẵn sang URL ảnh").',
  '',
  'insert into foods (id, name, category, image_url, display_order, is_active)',
  'values'
];

sql.push(
  rows
    .map(
      (r) =>
        `  ('${esc(r.id)}', '${esc(r.name)}', '${r.category}', ${
          r.image_url ? `'${esc(r.image_url)}'` : 'null'
        }, ${r.display_order}, true)`
    )
    .join(',\n')
);

sql.push(
  'on conflict (id) do update set',
  '  name = excluded.name,',
  '  category = excluded.category,',
  '  image_url = excluded.image_url,',
  '  display_order = excluded.display_order;'
);

const outDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
writeFileSync(path.join(outDir, 'supabase', 'seed_foods.sql'), sql.join('\n') + '\n', 'utf8');
writeFileSync(
  path.join(outDir, 'public', 'foods.json'),
  JSON.stringify(rows.map(({ id, name, category, display_order }) => ({ id, name, category, display_order })), null, 2),
  'utf8'
);

console.log(`Extracted ${rows.length} foods (${DATA.rice.length} rice, ${DATA.breakfast.length} breakfast).`);
console.log('Wrote supabase/seed_foods.sql and public/foods.json');
